FROM nvidia/cuda:13.0.2-cudnn-runtime-ubuntu24.04

ARG DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt update && apt install -y \
    git \
    libsndfile1-dev \
    tesseract-ocr \
    espeak-ng \
    python3 \
    python3-pip \
    ffmpeg \
    curl \
    build-essential \
    && rm -rf  /var/lib/apt/lists/*


COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv